ARG BASE=ubuntu:22.04

FROM ${BASE} as build

ENV REDIS_VERSION 7.2.4
ENV MALLOC=libc

RUN apt-get update && apt-get install -y wget make build-essential \
    && wget "https://download.redis.io/releases/redis-$REDIS_VERSION.tar.gz" \
    && tar -xvzf "redis-$REDIS_VERSION.tar.gz" \
    && cd "redis-$REDIS_VERSION" \
    && make "MALLOC=$MALLOC"\
    && make install

EXPOSE 6379

WORKDIR /logs

CMD ["redis-server", "--protected-mode no"]